version: "3.9"

services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: syncopatedllm
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/data
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    # env:
      # REDIS_ARGS: "--requirepass mypassword"
    volumes:
      - ./redis/data:/data
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./chromadb/data:/chroma/chroma/
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - 8000:8000