# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in laudllm.gemspec

gem "rake", "~> 13.0"

gem "bundler"
gem "pry"
gem "pry-doc"
gem "pry-stack_explorer"
gem "rb_sys"
gem "rspec"
gem "rubocop"
gem "stream_lines"
gem "hashie"
gem "beckett"
gem "chroma-db"
gem "cohere"
gem "cohere-ruby"
gem "composable_operations"
gem "dotenv"
gem "drydock"
gem "dry-monads"
gem 'dry-initializer'
gem "engtagger"
gem "google_palm_api"
gem "hexapdf"
gem "highline"
gem "json"
gem "jsonl"
gem "kramdown"
gem "langchainrb"
gem "lemmatizer"
gem "llm_memory"
gem "logging"
gem "mimemagic"
gem "networkx"
gem "nokogiri"
gem "ohm"
gem "ohm-contrib"
gem "open3"
gem "open4"
gem "open-uri"
gem "optimist"
gem "osc-ruby"
gem "parallel"
gem "pdf_paradise"
gem "pdf-reader"
gem "pgvector"
gem "polars"
gem "polars-df"
gem "poppler"
gem "pragmatic_segmenter"
gem "pragmatic_tokenizer"
gem "redcarpet"
gem "redic"
gem "redis"
gem "ruby-lsp"
gem "ruby-openai"
gem "ruby-spacy"
gem "safe_ruby"
gem "sequel"
gem "solargraph"
gem "summarize"
gem "syntax_tree"
gem "tomoto"
gem "tty-config"
gem "tty-prompt"
gem "typecheck"
gem 'yajl-ruby', require: 'yajl'
gem "httparty"
gem "vega"
gem "verbal_expressions"
gem "wordnet"
gem "wordnet-defaultdb"
